-- MySQL Script generated by MySQL Workbench
-- Sun Jan  7 12:59:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema web-store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema web-store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web-store` DEFAULT CHARACTER SET utf8 ;
USE `web-store` ;

-- -----------------------------------------------------
-- Table `web-store`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web-store`.`categories` (
  `category_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `category_id_UNIQUE` (`category_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `web-store`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web-store`.`users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `role` INT(11) NOT NULL,
  `verified` TINYINT(1) NOT NULL,
  `address` VARCHAR(50) NULL DEFAULT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `registration_date` DATE NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `web-store`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web-store`.`items` (
  `item_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `price` INT(11) NOT NULL,
  `available` CHAR(1) NOT NULL,
  `category_category_id` INT(11) NOT NULL,
  `picture` VARCHAR(300) NULL DEFAULT NULL,
  `users_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC) VISIBLE,
  INDEX `item_category_fk` (`category_category_id` ASC) VISIBLE,
  INDEX `fk_items_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `item_category_fk`
    FOREIGN KEY (`category_category_id`)
    REFERENCES `web-store`.`categories` (`category_id`),
  CONSTRAINT `fk_items_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `web-store`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `web-store`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web-store`.`orders` (
  `order_id` INT(11) NOT NULL AUTO_INCREMENT,
  `date_creation` DATE NOT NULL,
  `status` VARCHAR(100) NOT NULL,
  `total_cost` VARCHAR(45) NULL DEFAULT NULL,
  `users_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`order_id`, `users_user_id`),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC) VISIBLE,
  INDEX `fk_orders_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `web-store`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `web-store`.`item_lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web-store`.`item_lists` (
  `item_list_id` INT(11) NOT NULL AUTO_INCREMENT,
  `amount` VARCHAR(45) NOT NULL,
  `orders_order_id` INT(11) NOT NULL,
  `items_item_id` INT(11) NOT NULL,
  PRIMARY KEY (`item_list_id`, `items_item_id`),
  UNIQUE INDEX `item_list_id_UNIQUE` (`item_list_id` ASC) VISIBLE,
  INDEX `fk_item_lists_orders_idx` (`orders_order_id` ASC) VISIBLE,
  INDEX `fk_item_lists_items1_idx` (`items_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_item_lists_items1`
    FOREIGN KEY (`items_item_id`)
    REFERENCES `web-store`.`items` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_lists_orders`
    FOREIGN KEY (`orders_order_id`)
    REFERENCES `web-store`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
